---
apiVersion: v1
kind: Service
metadata:
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app: compose-post-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app: compose-post-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-redis
  labels:
    death-star-project: social-network
    app: compose-post-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: compose-post-redis
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: compose-post-redis
      name: compose-post-redis
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: micro-service
                    operator: In
                    values:
                      - set-1
              topologyKey: kubernetes.io/hostname
      containers:
      - name: compose-post-redis
        image: redis
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
