---
apiVersion: v1
kind: Service
metadata:
  name: media-memcached
  labels:
    death-star-project: social-network
    app: media-memcached
  namespace: social-network
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: social-network
    app: media-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-memcached
  labels:
    death-star-project: social-network
    app: media-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-memcached
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: media-memcached
      name: media-memcached
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: micro-service
                    operator: In
                    values:
                      - set-1
              topologyKey: kubernetes.io/hostname
      containers:
      - name: media-memcached
        image: memcached
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
