---
apiVersion: v1
kind: Service
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app: media-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: media-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app: media-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: media-mongodb
      name: media-mongodb
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: micro-service
                    operator: In
                    values:
                      - set-1
              topologyKey: kubernetes.io/hostname
      containers:
      - name: media-mongodb
        image: mongo:4.4.6
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: my-data
        emptyDir: {}
