---
apiVersion: v1
kind: Service
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: text-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: text-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: text-service
      name: text-service
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: micro-service
                    operator: In
                    values:
                      - set-1
              topologyKey: kubernetes.io/hostname
      containers:
      - name: text-service
        image: yg397/social-network-microservices:root_cause-del
        command: ["TextService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
