---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    death-star-project: social-network
    app: ubuntu-client
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: ubuntu-client
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: ubuntu-client
      name: ubuntu-client
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: micro-service
                    operator: In
                    values:
                      - set-1
              topologyKey: kubernetes.io/hostname
      containers:
      - name: ubuntu-client
        image: ubuntu
        resources:
          requests:
            cpu: 1
            memory: 2Gi
            ephemeral-storage: 2Gi
        command:  ["/bin/sh", "-c"]
        args:
          - apt-get -y update &&
            apt-get -y upgrade &&
            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
            luarocks install luasocket &&
            sleep 365d
        imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
