---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-redis
  labels:
    death-star-project: social-network
    app: user-timeline-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app: user-timeline-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-timeline-redis
  labels:
    death-star-project: social-network
    app: user-timeline-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: user-timeline-redis
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPU: "1"
#        sidecar.istio.io/proxyCPULimit: "2"
#        sidecar.istio.io/proxyMemory: 1Gi
#        sidecar.istio.io/proxyMemoryLimit: 2Gi
      labels:
        death-star-project: social-network
        app: user-timeline-redis
        micro-service: user-timeline
      name: user-timeline-redis
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: micro-service
                    operator: In
                    values:
                      - set-2
              topologyKey: kubernetes.io/hostname
      containers:
      - name: user-timeline-redis
        image: redis
        resources:
          requests:
            cpu: 3
            memory: 2Gi
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
