---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app: user-timeline-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: user-timeline-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-timeline-mongodb
  labels:
    death-star-project: social-network
    app: user-timeline-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: user-timeline-mongodb
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/proxyCPU: "1"
#        sidecar.istio.io/proxyCPULimit: "2"
#        sidecar.istio.io/proxyMemory: 1Gi
#        sidecar.istio.io/proxyMemoryLimit: 2Gi
      labels:
        death-star-project: social-network
        app: user-timeline-mongodb
        micro-service: user-timeline
      name: user-timeline-mongodb
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: micro-service
                    operator: In
                    values:
                      - set-2
              topologyKey: kubernetes.io/hostname
      containers:
      - name: user-timeline-mongodb
        image: mongo:4.4.6
        resources:
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: my-data
        emptyDir: {}
